### ISSUE TITLE
Halaman Input Update Nilai

### ISSUE THREAD

**Issue by ilomon10** [Pi-Laboratory/akademik-frontend#33]
@ridhowise  Beking akang halaman input dan update nilai, nnti kse gabung di halaman jadwal kelas pe tab

**Comment by ilomon10** [comment]
Di tab kelas halaman jadwal kelas, tambah akang dp info kurikulum

**Comment by ridhowise** [comment]
kita da update presensi dan nilai lo, di pull request ini
